/* SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda. */
/* SPDX-License-Identifier: LGPL-2.1-only */
#include "../../src/board_internal.h"
#include <emscripten/emscripten.h>
#include <emscripten/html5.h>
#include <stdlib.h>

typedef struct BoardWebState { float scale; } BoardWebState;
static BoardWebState *board_web(BoardBackend *backend) { return backend ? (BoardWebState *)backend->implementation : NULL; }
static void board_web_emit(BoardBackend *backend, BoardEvent *event) { if (backend && backend->event_sink) backend->event_sink(backend->event_data, event); }
static BoardPointerButton board_web_button(short button) { return button == 0 ? BOARD_POINTER_BUTTON_LEFT : button == 1 ? BOARD_POINTER_BUTTON_MIDDLE : button == 2 ? BOARD_POINTER_BUTTON_RIGHT : BOARD_POINTER_BUTTON_NONE; }
static void board_web_resize(BoardBackend *backend) { BoardWebState *state = board_web(backend); double width = 0, height = 0; uint32_t pixel_width, pixel_height; float scale; BoardEvent event = {sizeof(BoardEvent), BOARD_ABI_VERSION, BOARD_EVENT_RESIZE, 0, {{0}}}; if (!state) return; emscripten_get_element_css_size("#canvas", &width, &height); if (width <= 0 || height <= 0) return; scale = (float)emscripten_get_device_pixel_ratio(); pixel_width = (uint32_t)(width * scale + .5); pixel_height = (uint32_t)(height * scale + .5); if (!pixel_width || !pixel_height) return; if (backend->width == pixel_width && backend->height == pixel_height && backend->scale == scale) return; state->scale = scale; backend->width = pixel_width; backend->height = pixel_height; backend->scale = scale; emscripten_set_canvas_element_size("#canvas", backend->width, backend->height); event.data.resize.width = backend->width; event.data.resize.height = backend->height; event.data.resize.scale = backend->scale; board_web_emit(backend, &event); }
static EM_BOOL board_web_resize_callback(int type, const EmscriptenUiEvent *event, void *data) { (void)type; (void)event; board_web_resize((BoardBackend *)data); return EM_TRUE; }
static EM_BOOL board_web_mouse(int type, const EmscriptenMouseEvent *input, void *data) { BoardBackend *backend = data; BoardWebState *state = board_web(backend); BoardEvent event = {sizeof(BoardEvent), BOARD_ABI_VERSION, BOARD_EVENT_POINTER_MOVE, 0, {{0}}}; if (!state) return EM_FALSE; event.type = type == EMSCRIPTEN_EVENT_MOUSEDOWN ? BOARD_EVENT_POINTER_DOWN : type == EMSCRIPTEN_EVENT_MOUSEUP ? BOARD_EVENT_POINTER_UP : BOARD_EVENT_POINTER_MOVE; event.data.pointer.x = input->targetX * state->scale; event.data.pointer.y = input->targetY * state->scale; event.data.pointer.pointer_id = 0; event.data.pointer.button = board_web_button(input->button); board_web_emit(backend, &event); return EM_TRUE; }
static EM_BOOL board_web_touch(int type, const EmscriptenTouchEvent *input, void *data) { BoardBackend *backend = data; BoardWebState *state = board_web(backend); const EmscriptenTouchPoint *touch; BoardEvent event = {sizeof(BoardEvent), BOARD_ABI_VERSION, BOARD_EVENT_POINTER_MOVE, 0, {{0}}}; int i; if (!state || !input->numTouches) return EM_FALSE; touch = &input->touches[0]; for (i = 0; i < input->numTouches; ++i) if (input->touches[i].isChanged) { touch = &input->touches[i]; break; } event.type = type == EMSCRIPTEN_EVENT_TOUCHSTART ? BOARD_EVENT_POINTER_DOWN : type == EMSCRIPTEN_EVENT_TOUCHEND ? BOARD_EVENT_POINTER_UP : type == EMSCRIPTEN_EVENT_TOUCHCANCEL ? BOARD_EVENT_POINTER_CANCEL : BOARD_EVENT_POINTER_MOVE; event.data.pointer.x = touch->targetX * state->scale; event.data.pointer.y = touch->targetY * state->scale; event.data.pointer.pointer_id = (uint32_t)touch->identifier; event.data.pointer.button = BOARD_POINTER_BUTTON_LEFT; board_web_emit(backend, &event); return EM_TRUE; }
static EM_BOOL board_web_key(int type, const EmscriptenKeyboardEvent *input, void *data) { BoardEvent event = {sizeof(BoardEvent), BOARD_ABI_VERSION, type == EMSCRIPTEN_EVENT_KEYDOWN ? BOARD_EVENT_KEY_DOWN : BOARD_EVENT_KEY_UP, 0, {{0}}}; event.data.key.key = input->keyCode; event.data.key.repeat = input->repeat; board_web_emit((BoardBackend *)data, &event); return EM_FALSE; }
static void board_web_frame(void *data) { BoardBackend *backend = data; if (!backend || !backend->scheduler.running) { emscripten_cancel_main_loop(); return; } board_scheduler_request_frame(&backend->scheduler); board_backend_step(backend, (uint64_t)(emscripten_get_now() * 1000000.0)); }
static BoardResult board_web_run(BoardBackend *backend, BoardEventSink sink, void *data) { (void)sink; (void)data; if (!backend) return BOARD_ERROR_INVALID_ARGUMENT; emscripten_set_main_loop_arg(board_web_frame, backend, 0, EM_TRUE); return BOARD_OK; }
static void board_web_dispose(BoardBackend *backend) { free(backend->implementation); backend->implementation = NULL; }
BoardResult board_web_backend_init(BoardBackend *backend, const BoardBackendConfig *config) { BoardWebState *state; if (!backend || !config) return BOARD_ERROR_INVALID_ARGUMENT; state = calloc(1, sizeof(*state)); if (!state) return BOARD_ERROR_OUT_OF_MEMORY; backend->implementation = state; backend->width = config->width; backend->height = config->height; backend->scale = 1; backend->surface.web = (BoardSurfaceWebInterface){sizeof(BoardSurfaceWebInterface), BOARD_ABI_VERSION, "#canvas", state}; emscripten_set_resize_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, backend, EM_TRUE, board_web_resize_callback); emscripten_set_mousedown_callback("#canvas", backend, EM_TRUE, board_web_mouse); emscripten_set_mousemove_callback("#canvas", backend, EM_TRUE, board_web_mouse); emscripten_set_mouseup_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, backend, EM_TRUE, board_web_mouse); emscripten_set_touchstart_callback("#canvas", backend, EM_TRUE, board_web_touch); emscripten_set_touchmove_callback("#canvas", backend, EM_TRUE, board_web_touch); emscripten_set_touchend_callback("#canvas", backend, EM_TRUE, board_web_touch); emscripten_set_touchcancel_callback("#canvas", backend, EM_TRUE, board_web_touch); emscripten_set_keydown_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, backend, EM_TRUE, board_web_key); emscripten_set_keyup_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, backend, EM_TRUE, board_web_key); board_web_resize(backend); backend->run = board_web_run; backend->dispose = board_web_dispose; return BOARD_OK; }
