/* SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda. */
/* SPDX-License-Identifier: LGPL-2.1-only */
#include "../../src/magic_context_private.h"
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct MagicMetalBackend { CAMetalLayer *layer; id<MTLDevice> device; id<MTLCommandQueue> queue; id<CAMetalDrawable> drawable; uint32_t width, height; float scale; char version[128]; } MagicMetalBackend;
static MagicResult magic_metal_board_result(BoardResult result) { return result == BOARD_OK ? MAGIC_OK : result == BOARD_ERROR_VERSION ? MAGIC_ERROR_VERSION : result == BOARD_ERROR_UNAVAILABLE ? MAGIC_ERROR_UNAVAILABLE : MAGIC_ERROR_SURFACE; }
extern "C" MagicResult magic_metal_backend_create(MagicContext *context, BoardNativeSurface *surface) { BoardSurfaceMetalInterface capability = {}; MagicMetalBackend *backend; BoardResult result; if (!context || !surface) return MAGIC_ERROR_INVALID_ARGUMENT; result = board_surface_query_interface(surface, BOARD_SURFACE_INTERFACE_METAL, BOARD_ABI_VERSION, &capability, sizeof(capability)); if (result != BOARD_OK) return magic_metal_board_result(result); backend = (MagicMetalBackend *)calloc(1, sizeof(*backend)); if (!backend) return MAGIC_ERROR_OUT_OF_MEMORY; backend->layer = (__bridge CAMetalLayer *)capability.layer; backend->device = MTLCreateSystemDefaultDevice(); backend->queue = [backend->device newCommandQueue]; if (!backend->layer || !backend->device || !backend->queue) { [backend->queue release]; [backend->device release]; free(backend); return MAGIC_ERROR_UNAVAILABLE; } snprintf(backend->version, sizeof(backend->version), "%s", [[backend->device name] UTF8String]); backend->layer.device = backend->device; backend->layer.pixelFormat = MTLPixelFormatBGRA8Unorm; backend->layer.framebufferOnly = YES; backend->width = capability.width; backend->height = capability.height; backend->scale = capability.scale; backend->layer.drawableSize = CGSizeMake(backend->width, backend->height); context->backend_data = backend; return MAGIC_OK; }
extern "C" void magic_metal_backend_destroy(MagicContext *context) { MagicMetalBackend *backend = context ? (MagicMetalBackend *)context->backend_data : nil; if (backend) { [backend->drawable release]; [backend->queue release]; [backend->device release]; free(backend); context->backend_data = NULL; } }
extern "C" const char *magic_metal_backend_version(const MagicContext *context) { const MagicMetalBackend *backend = context ? (const MagicMetalBackend *)context->backend_data : nil; return backend && backend->version[0] ? backend->version : "unknown"; }
extern "C" MagicResult magic_metal_backend_resize(MagicContext *context, uint32_t width, uint32_t height, float scale) { MagicMetalBackend *backend = context ? (MagicMetalBackend *)context->backend_data : nil; if (!backend || !width || !height) return MAGIC_ERROR_INVALID_ARGUMENT; backend->width = width; backend->height = height; backend->scale = scale > 0 ? scale : 1; backend->layer.contentsScale = backend->scale; backend->layer.drawableSize = CGSizeMake(width, height); return MAGIC_OK; }
extern "C" MagicResult magic_metal_backend_begin_frame(MagicContext *context, MagicFrame *frame) { MagicMetalBackend *backend = context ? (MagicMetalBackend *)context->backend_data : nil; if (!backend || !frame) return MAGIC_ERROR_INVALID_ARGUMENT; backend->drawable = nil; frame->metal = (MagicMetalInterop){ sizeof(MagicMetalInterop), MAGIC_ABI_VERSION, (__bridge void *)backend->layer, (__bridge void *)backend->device, (__bridge void *)backend->queue, (const void **)&backend->drawable, backend->width, backend->height, backend->scale }; return MAGIC_OK; }
extern "C" MagicResult magic_metal_backend_end_frame(MagicContext *context, MagicFrame *frame) { MagicMetalBackend *backend = context ? (MagicMetalBackend *)context->backend_data : nil; (void)frame; if (!backend) return MAGIC_ERROR_INVALID_ARGUMENT; if (backend->drawable) { id<MTLCommandBuffer> command = [backend->queue commandBuffer]; [command presentDrawable:backend->drawable]; [command commit]; [backend->drawable release]; backend->drawable = nil; } return MAGIC_OK; }
